#!/usr/bin/python3
import sys

def factorize(num):
    for i in range(2, num):
        if num % i == 0:
            return i, num // i
    return None

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("Usage: factors <file>")
        sys.exit(1)

    filename = sys.argv[1]
    with open(filename) as f:
        for line in f:
            num = int(line.strip())
            factors = factorize(num)
            if factors:
                print(f"{num}={factors[0]}*{factors[1]}")
